language: go
sudo: false
matrix:
  include:
  - go: 1.x
    env: LATEST=true
  - go: tip
  allow_failures:
  - go: tip
before_install:
- go get github.com/mitchellh/gox
install:
- 
script:
- go get -t -v ./...
- if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -verbose
  ./...; fi
deploy:
  provider: releases
  file:
  - oget_windows_amd64.exe
  - oget_linux_amd64
  - oget_darwin_amd64
  skip_cleanup: true
  on:
    repo: artificerpi/oget
    tags: true
    condition: "$LATEST = true"
  api-key:
    secure: ZkIIreVXBRdBNeC2eIyqJJ13vXxguXfQFSvbn3iyDsRmGIcplPGfjUpaZoNNWp05YnbVDmLwRR/OjoZV1AmlOshzD8I6Z21NMYGQZ/UqjGhMwHJYNfd2FpGUFTJToNfxtoem+Cdnp9CQLOlRYKnjJpgXRFZ74YXGaDrCeklXrFpXfY4vNKV4heW98KeVSGmn6sLu8s2X/9ELa7+0zOEE9nVnEVlDxLLVOiBfdPp8W/GHrr0NINyLUFGRHJvyRRPuwUfQqGej8btgDxpWs0cPrKhWtSI9XA6gNIfnlhp0lqjBslzR49tnbzN2MLAG5pYBgMqV223BihaJeL2YHlur+IXQ+4JV4uX1Iv7ZwjQMqyj68H+vRXVkg6GCsyL19eXBKnUAqoDmsZJKDLZakpADVJYbLCbIX8ALRFoXKlSNE2GYFVeJFp0RSstkaamtxxgSRYmWPXheaknnSO81fkJanmT9TG6ehRQeh7DyiVYoggsIq8hvLYokaAuhW/FSWHT5qncrs3MphzX1/ehz1vGWaqEH9E6fN1OLJ0tQWu91pOCKNnntNd0+gA2yTuORxIKLT9Fi26LvV82Fxxyzp2nFPC5yNzW2ShnwIOkp0KSk6NRKupqEJfbOn1sIcJl2FPoicg4RR2rt5pCbLpshjP6MhtXtfw7Mr/SLeLUAW9A6Nj4=
